- name: Build Xcode Project
        script: |
          # تنظيف
          xcodebuild clean -project "Unity-iPhone.xcodeproj" -scheme "Unity-iPhone"
          
          # البناء مع تحديث التوقيع تلقائياً
          xcodebuild archive -project "Unity-iPhone.xcodeproj" -scheme "Unity-iPhone" \
            -sdk iphoneos \
            -archivePath $PWD/build/Unity-iPhone.xcarchive \
            -allowProvisioningUpdates
          
          # التصدير
          xcodebuild -exportArchive -archivePath $PWD/build/Unity-iPhone.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist exportOptions.plist
